from app.subtitle_files import save_sidecar_xml

metadata = {
            'mediaObjectId': '70af6a77d62e42dfa2c87b037458400f5c1943debc864537b24c31a56c38bbec',
            'externalId': 'qsf7664p39',
            'title': 'QAS 20.1 ingest test - Fietsstraten in centrum Gent',
            'description': 'QAS 20.1 ingest test',
            'date': '2019:05:28 09:34:30',
            'originalFileName': 'qsf7664p39.mp4',
            'width': 630,
            'height': 360,
            'keywords': [],
            'type': 'Video',
            'authors': [],
            'lastModifiedDate': '2020-10-15T09:29:28Z',
            'archiveDate': '2020-06-19T10:56:45Z',
            'exportable': True,
            'editable': True,
            'deletable': True,
            'isPublic': False,
            'ingestSpaceId': '',
            'isInIngestSpace': False,
            'status': 'FINISHED',
            'browseStatus': None,
            'originalStatus': 'completed',
            'archiveStatus': 'on_disk',
            'workflow': 'borndigital',
            'mdProperties': [{'value': [{'value': 'qsvx05z57z',
                                         'attribute': 'is_verwant_aan',
                                         'dottedKey': None}],
                              'attribute': 'dc_relations',
                              'dottedKey': None},
                             {'value': [{'value': 'QAS_20.mp4',
                                         'attribute': 'Bestandsnaam',
                                         'dottedKey': None}],
                              'attribute': 'dc_identifier_localids',
                              'dottedKey': None},
                             {'subKey': 'multiselect',
                              'value': [{'value': 'VIAA-ONDERWIJS',
                                         'attribute': 'multiselect',
                                         'dottedKey': None},
                                        {'value': 'VIAA-ONDERZOEK',
                                         'attribute': 'multiselect',
                                         'dottedKey': None},
                                        {'value': 'VIAA-INTRA_CP-CONTENT',
                                         'attribute': 'multiselect',
                                         'dottedKey': None},
                                        {'value': 'VIAA-INTRA_CP-METADATA-ALL',
                                         'attribute': 'multiselect',
                                         'dottedKey': None},
                                        {'value': 'VIAA-PUBLIEK-METADATA-LTD',
                                         'attribute': 'multiselect',
                                         'dottedKey': None}],
                              'attribute': 'dc_rights_licenses',
                              'dottedKey': None},
                             {'value': 'QAS 20.1 ingest test - Fietsstraten in centrum Gent',
                              'attribute': 'dc_title',
                              'dottedKey': None},
                             {'value': 'OR-h41jm06',
                              'attribute': 'Original_CP_ID',
                              'dottedKey': None},
                             {'value': 'QAS_20.mp4',
                              'attribute': 'dc_source',
                              'dottedKey': None},
                             {'value': 'QAS 20.1 ingest test',
                              'attribute': 'dc_description',
                              'dottedKey': None},
                             {'value': 'qsf7664p39',
                              'attribute': 'PID',
                              'dottedKey': None},
                             {'value': 'testbeeld',
                              'attribute': 'CP',
                              'dottedKey': None},
                             {'value': '2019:05:28 09:34:30',
                              'attribute': 'CreationDate',
                              'dottedKey': None},
                             {'value': 'AVS',
                              'attribute': 'Original_CP',
                              'dottedKey': None},
                             {'value': 'OR-h41jm1d',
                              'attribute': 'CP_id',
                              'dottedKey': None},
                             {'value': '08_H264',
                              'attribute': 'dc_identifier_localid',
                              'dottedKey': None},
                             {'value': 'MP4 Sound Media Handler',
                              'attribute': 'RightsOwner',
                              'dottedKey': None},
                             {'value': 'borndigital',
                              'attribute': 'sp_name',
                              'dottedKey': None}],
            'relations': {}}

tp = {
    'pid': 'qsf7664p39',
    'subtitle_type': 'closed',
    'srt_file': 'qsf7664p39_closed.srt',
    'vtt_file': 'qsf7664p39.vtt',
    'xml_file': None,
    'xml_sidecar': None,
    'mh_response': None,
    'mam_data': '{}',
    'replace_existing': None,
    'transfer_method': 'ftp'}


xml_filename, xml_data = save_sidecar_xml("app/subtitle_uploads", metadata, tp)

print("xmldata=\n", xml_data)
